import type { Metadata } from "next";
import { Chakra_Petch, Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { NuqsAdapter } from "nuqs/adapters/next";
import Providers from "./providers";

const chakraPetch = Chakra_Petch({
  variable: "--font-chakra-petch",
  weight: ["700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chakraPetch.variable} ${inter.variable} antialiased mx-auto max-w-7xl p-16`}
      >
        <Providers>
          <NuqsAdapter>
            <Header />
            {children}
          </NuqsAdapter>
        </Providers>
      </body>
    </html>
  );
}
